# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: IARM CI/CD

on:
  push:
    branches:
      - IARM_azure-deploy
  pull_request:
    branches:
      - IARM_azure-deploy
  workflow_dispatch:

jobs:
  build_backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Zip Backend app
        run: zip -r fastapi-app.zip ./fastapi-app ./requirements.txt ./startup.sh ./.gitignore ./.github

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iarm-artifacts
          path: |
            fastapi-app.zip
            !venv/

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_backend
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: iarm-artifacts

      - name: Unzip artifact for deployment
        run: unzip fastapi-app.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E1155298B936432BB96AB77966B3A58C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1DF2DDC88F7D481F974A29B0A4ABD5FD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FD2BF01332D749ED80A41DD37C049CDA }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'iarm-backend-api'
          slot-name: 'Production'

  build_windows_electron-app:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: build_backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: |
          cd electron-app
          npm install

      - name: Build Electron App for Windows
        run: |
          cd electron-app
          npm run build:win

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: electron-windows
          path: electron-app/dist/*.exe
  
  Release_Project:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    needs: [deploy_backend, build_windows_electron-app]
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: iarm-artifacts

      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: electron-windows
      
      - name: Create zip for release
        run: |
          mkdir release
          mv fastapi-app.zip release/
          mv *.exe release/
          cd release
          zip -r iarm-release.zip .

      - name: Test artifact download
        run: ls -R
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: IARM Release v${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          files: release/iarm-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  repository_mirroring:
    runs-on: ubuntu-latest
    needs: [deploy_backend, build_windows_electron-app, Release_Project]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:EpitechPromo2026/G-EIP-700-PAR-7-1-eip-yvain.ye.git
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}