# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: IARM CI/CD

on:
  push:
    branches:
      - IARM_azure-deploy
  pull_request:
    branches:
      - IARM_azure-deploy
  workflow_dispatch:

jobs:
  build_backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Zip Backend app
        run: zip -r fastapi-app.zip ./fastapi-app

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iarm-artifacts
          path: |
            fastapi-app.zip
            !venv/

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_backend
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: iarm-artifacts

      - name: Unzip artifact for deployment
        run: unzip fastapi-app.zip

      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'iarm-backend-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F1CDCBE8F1B74160BF1F8F1AD7FEAE8B }}

  build_windows_electron-app:
    runs-on: windows-latest
    needs: build_backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: |
          cd electron-app
          npm install

      - name: Build Electron App for Windows
        run: |
          cd electron-app
          npm run build:win

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: electron-windows
          path: electron-app/dist/*.exe